version: "3.9"
services:
  backend:
    build: ./backend
    environment:
      - NODE_ENV=production
      - PORT=4000
      - CORS_ORIGIN=http://localhost:5173
    ports:
      - "4000:4000"
    restart: unless-stopped

  frontend:
    build: ./frontend
    environment:
      - VITE_API_BASE=http://93.115.203.113:4000
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: unless-stopped

  n8n:
    image: docker.n8n.io/n8nio/n8n:1.111.0
    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=http://localhost:5678/
      - GENERIC_TIMEZONE=Europe/Moscow
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
    restart: unless-stopped

volumes:
  n8n_data:
